apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-demo
  template: 
    metadata:
      name: ubuntu-pod
      labels:
        app: ubuntu-demo
    spec:
      containers:
      - name: ubuntu-container
        image: registry.cn-hangzhou.aliyuncs.com/ryang-test/ubuntu:24.04 #ubuntu:latest
        # command: ["sleep", "3600"]  # Sleep for 3600s
        # Get into the pod, replace with
        command: ["/bin/bash"]
        args: ["-c", "trap : TERM INT; sleep infinity & wait"]
        env:
        - name: ENV_VAR_NAME
          value: "value"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pvc1
          mountPath: "/mnt1"
        - name: app-data
          mountPath: /usr/src/app
        - name: pvc2
          mountPath: "/mnt2"
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: pvc1
        persistentVolumeClaim:
          claimName: rwx-test-claim
      - name: app-data
        hostPath:
          path: /var/home/sysadmin/localKLBase/
          type: Directory
      - name: pvc2
        persistentVolumeClaim:
          claimName: qanything-resource

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-test-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs
