apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: etcd
    app: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: etcd
        app: etcd
    spec:
      containers:
        - args:
            - etcd
            - -advertise-client-urls=http://127.0.0.1:2379
            - -listen-client-urls
            - http://0.0.0.0:2379
            - --data-dir
            - /etcd
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_SNAPSHOT_COUNT
              value: "50000"
          image: registry.cn-hangzhou.aliyuncs.com/ryang-test/etcd:v3.5.5 #quay.io/coreos/etcd:v3.5.5
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 20
          name: milvus-etcd-local
          imagePullSecrets:
            - name: regcred
          volumeMounts:
            - mountPath: /etcd
              name: etcd-claim0
      restartPolicy: Always
      volumes:
        - name: etcd-claim0
          persistentVolumeClaim:
            claimName: etcd-claim0



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: etcd-claim0
  name: etcd-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
spec:
  ports:
  - port: 2379  
    targetPort: 2379  
  selector:
    app: etcd
