apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  securityContext:
    runAsUser: 0  # 设置为0表示以root用户运行
  containers:
    - command: ["/bin/bash"]
      args: ["-c", "mkdir -p /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins && chown -R elasticsearch:elasticsearch /usr/share/elasticsearch && su elasticsearch -c '/usr/share/elasticsearch/bin/elasticsearch'"]
      env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
      image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
      livenessProbe:
        exec:
          command: 
          - sh
          - -c
          - |
            #!/user/bin/env bash
            curl --fail http://localhost:9200/_cat/health || exit 1
        failureThreshold: 3
        periodSeconds: 10
        timeoutSeconds: 20
      name: es-container-local
      ports:
        - containerPort: 9210
          protocol: TCP
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/plugins
          name: elasticsearch-plugin
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-claim1
  restartPolicy: OnFailure
  volumes:
    - name: elasticsearch-plugin
      persistentVolumeClaim:
        claimName: elasticsearch-plugin
    - name: elasticsearch-claim1
      persistentVolumeClaim:
        claimName: elasticsearch-claim1



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: elasticsearch-claim1
  name: elasticsearch-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9210
  selector:
    io.kompose.service: elasticsearch
