apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: local-models
  name: local-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
