apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --max-connections=10000
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          image: registry.cn-hangzhou.aliyuncs.com/ryang-test/mysql:8.4
          name: mysql-container-local
          ports:
            - containerPort: 3306
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0




---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
    - name: "3316"
      port: 3316
      targetPort: 3306
  selector:
    io.kompose.service: mysql



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-claim0
  name: mysql-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
