apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  containers:
    - args:
        - /bin/bash
        - -c
        - |2
            mkdir -p /usr/share/elasticsearch/data /usr/share/elasticsearch/plugins &&
            chown -R elasticsearch:elasticsearch /usr/share/elasticsearch &&
            su elasticsearch -c '/usr/share/elasticsearch/bin/elasticsearch'
      env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
      image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
      livenessProbe:
        exec:
          command:
            - curl --fail http://localhost:9200/_cat/health || exit 1
        failureThreshold: 3
        periodSeconds: 10
        timeoutSeconds: 20
      name: es-container-local
      ports:
        - containerPort: 9200
          protocol: TCP
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/plugins
          name: elasticsearch-claim0
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-claim1
  restartPolicy: OnFailure
  volumes:
    - name: elasticsearch-claim0
      persistentVolumeClaim:
        claimName: elasticsearch-claim0
    - name: elasticsearch-claim1
      persistentVolumeClaim:
        claimName: elasticsearch-claim1
