apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --max-connections=10000
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          image: mysql:8.4
          name: mysql-container-local
          ports:
            - containerPort: 3306
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
