apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: qanything-resource
  name: qanything-resource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
