apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: standalone
  name: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: standalone
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: standalone
    spec:
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: ETCD_ENDPOINTS
              value: etcd:2379
            - name: MINIO_ADDRESS
              value: minio:9000
          image: milvusdb/milvus:v2.4.8
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9091/healthz
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 20
          name: milvus-standalone-local
          ports:
            - containerPort: 19530
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: standalone-claim0
      restartPolicy: Always
      volumes:
        - name: standalone-claim0
          persistentVolumeClaim:
            claimName: standalone-claim0
