apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -v -f docker-compose-linux.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: standalone
  name: standalone
spec:
  ports:
    - name: "19540"
      port: 19540
      targetPort: 19530
  selector:
    io.kompose.service: standalone
